"""add practice_logs table

Revision ID: 30c062e750f5
Revises: 71ade783029e
Create Date: 2026-08-18 17:22:54.573016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '30c062e750f5'
down_revision: Union[str, None] = '71ade783029e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practice_logs',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('practiced_on', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'practiced_on', name='uq_practice_log_student_date')
    )
    op.create_index(op.f('ix_practice_logs_student_id'), 'practice_logs', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_practice_logs_student_id'), table_name='practice_logs')
    op.drop_table('practice_logs')
    # ### end Alembic commands ###
